version: "3.8"

services:
  client:
    env_file:
      - ./.env
    # image: 'horizon5132/approve-me-fe:latest'
    container_name: letsplay-fe-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $LOCAL_CLIENT_PORT:$DOCKER_CLIENT_PORT
      # - "80:80"
    networks:
      - letsplay_net
    volumes:
      - './src/resources/img:/var/www/letsplay/html/images'
      # - ./templates:/etc/nginx/templates
  # watchtower:
  #   image: containrrr/watchtower
  #   restart: unless-stopped
  #   networks:
  #     - mynet
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock # store log file
  #   command: --interval 100

networks:
  letsplay_net:
    external: true
    # driver: bridge
# volumes:
#   client:
